import React from 'react'
import { CiLock } from "react-icons/ci";
import { IoMdHappy } from "react-icons/io";
const page = () => {
  //later generated by ai
  const mood=["Happy","Sad","Excited","Angry","Love"]
  return (
    <div className=' p-5'>
       
     <div className=' bg-delektheme rounded-md space-y-2  text-gray-400 flex flex-col items-center p-5'>
      <p className=' hover:text-white text-sm transition'>Happy</p>
     <IoMdHappy className=' hover:text-yellow-300 transition' />
     </div>
     
    
      </div>
  )
}

export default page