import DiaryCard from '@/components/DiaryCard/DiaryCard'
import React from 'react'

const page = () => {
  //later generated by ai
  const mood=["Happy","Sad","Excited","Angry","Love"]
  return (
    <div className=' p-5'>
       
    <DiaryCard/>
    
      </div>
  )
}

export default page